language: java
jdk: oraclejdk8
branches:
  except:
    - legacy
    - experimental
addons:
  sonarqube: true
env:
  global:
    - secure:d043ef3ea7d081203e4eca0ac14b14d0054b6c43
script:
  - sonar-scanner -Dsonar.login=$SONAR_TOKEN
